### ISSUE TITLE
К добавлению

### ISSUE THREAD

**Issue by nicothin** [melnik909/frontend-whitelist#1]
https://github.com/nicothin/web-design — авторы внизу
далее несколько моих (Николай Громов):
https://github.com/nicothin/web-development/tree/master/git 
https://nicothin.github.io/sublime-text/sublime-text-3-hotkeys.html
https://nicothin.github.io/Atom/Atom-hotkeys.html

**Comment by web-padawan** [comment]
Подкину сюда же:

[Длинная телега про бутстрап](https://gist.github.com/iAdramelk/d328b73c72cab92ef95f)
[Чек-лист вёрстки. Что можно отдавать клиенту, а что надо переделывать](https://habrahabr.ru/post/114256/)
[Стандарты верстки компании JetStyle](http://jetstyle.github.io/html-guidelines/)
[CSSSR/sputnik](https://github.com/csssr/sputnik)

**Comment by nicothin** [comment]
Читал последнюю ссылку, раздел про CSS. Немного ужасался рекомендации использовать табы вместо пробелов и грамотности ))

**Comment by web-padawan** [comment]
@nicothin ну там у ребят своя атмосфера. До времен минификаторов табы имели смысл.

**Comment by web-padawan** [comment]
[Все способы вертикального выравнивания в CSS](https://habrahabr.ru/company/netcracker/blog/277433/)
[Очень простое руководство по CSS3-анимациям](http://frontender.info/ochen-prostoe-rukovodstvo-po-css-animatsiyam/)
[Как выбрать фреймворк для frontend-разработки](https://habrahabr.ru/post/277547/)
[Идеальная методология CSS-классов с учётом любых тонкостей интерфейсов](https://medium.com/@grawlcore/идеальная-методология-css-классов-с-учётом-любых-тонкостей-интерфейсов-e49e90d796e1)

**Comment by isqua** [comment]
[Краш-тест вёрстки. Как тестировать вёрстку на переполнение и как избежать проблем](https://isqua.ru/blog/2016/06/19/crash-test-viorstki/)

**Comment by melnik909** [comment]
@nicothin Спасибо за памятку для дизайнеров! Именно этого и не хватало

**Comment by melnik909** [comment]
@isqua А можете сказать имя и фамилию автора статьи "Краш-тест вёрстки"?

**Comment by isqua** [comment]
@melnik909, увы :)

**Comment by web-padawan** [comment]
+1  к статьям Ивана Салагаева (большинство его серии статей вполне актуальны и их стоит добавить)

**Comment by UsulPro** [comment]
Сделали перевод туториала "JavaScript Stack from Scratch", собравшее с октября [![GitHub stars](https://img.shields.io/github/stars/verekia/js-stack-from-scratch.svg?style=social&label=Star)](https://github.com/verekia/js-stack-from-scratch) автор @verekia

[Русская версия](https://github.com/UsulPro/js-stack-from-scratch)

Будем благодарны за поддержку)

PS автор готовит вторую версию руководства, будем переводить дальше

**Comment by melnik909** [comment]
@UsulPro Спасибо. Добавил

**Comment by rtxrulez** [comment]
Скорость рендеринга страниц: исследования, замеры, автоматизация
https://events.yandex.ru/lib/talks/232/

**Comment by nicothin** [comment]
Этому яндексовскому докладу 6 лет. ХЗ, стоит ли его включать.

**Comment by PVasili** [comment]
http://yandex.ru и http://google.ru с этих ссылок должно начинаться

**Comment by nicothin** [comment]
@PVasili у нас тут, вроде как, разработчики, ссылки на поисковики и материалы по навыкам работы с компьютерам несколько излишни )

**Comment by PVasili** [comment]
@nicothin если автор бережно собирает то, что устаревает через год-два, а теряет актуальность ещё быстрее то думаю, что стоит добавить поисковики. Уж его он точно не успеет их обогнать. Думаю, что лучше собрать поисковые фразы, для тех кто забыл как и что искать :)

**Comment by nicothin** [comment]
@PVasili если только автор сменит ник на @KO :D

**Comment by melnik909** [comment]
@PVasili Я стараюсь собирать доклады, который затрагивают фундаментальные темы. К примеру, урок из ШРИ "Модель отображения. Браузеры" Олега Мохова или доклад Вадима Макишвили "Ошибка. Осознание, примирение, извлечение пользы".
