### ISSUE TITLE
Отдельная иконка для видео

### ISSUE THREAD

**Issue by web-padawan** [melnik909/frontend-whitelist#6]
Сабж.  Надо визуально дать понять, какие из ссылок ведут на видео и на платные материалы (книги на озоне)
Хорошо бы также группировать источники по типу того как сделано [здесь](https://github.com/javascript-society/javascript-path)

**Comment by isqua** [comment]
Для видео 🎥 — `:movie_camera:`?

**Comment by melnik909** [comment]
@web-padawan Иконки для вида контента добавим.

**Comment by melnik909** [comment]
@web-padawan  Для статей, переводов и ресурсов сделать подписи ?

**Comment by melnik909** [comment]
@isqua я добавил подписи для большей ясности

**Comment by web-padawan** [comment]
Подпись в скобках надо еще прочитать, а иконка сразу заметна. 
Еще можно хеш-теги,  как [здесь](https://github.com/ericelliott/essential-javascript-links), но они тоже проигрывают иконкам в читаемости.

Книги я бы точно группировал в таблицы,  c указанием, какие из них платные.

**Comment by melnik909** [comment]
@web-padawan Я не вижу смысла:
1) Делать одну секцию в виде таблицы;
2) Добавлять иконку цены к книгам.

**Comment by web-padawan** [comment]
Насчет книг вопрос отдельный, по-иоему, ссылки на ozon не очень вписываютсч в формат подборки. Есть ряд книг, выложенных авторами для бесплатного чтения в онлайне, такие точно стоит добавлять. Но книги в том же JS path хорошо представлены. Я бы больше концентрировался на статьях / видео (и в каждой секции материалы можно упорядочить соответственно).
